# Generated by Django 4.0.5 on 2022-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
