# Generated by Django 4.0.5 on 2022-06-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_alter_beer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
